kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
    name: silver-claim
spec: 
    accessModes: 
    - ReadWriteOnce
    resources: 
        requests: 
            storage: 3Gi
    storageClassName: nutanix-volume 
